# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: release-1.31
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes.client.models.v1alpha1_lease_candidate_spec import V1alpha1LeaseCandidateSpec

class TestV1alpha1LeaseCandidateSpec(unittest.TestCase):
    """V1alpha1LeaseCandidateSpec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1alpha1LeaseCandidateSpec:
        """Test V1alpha1LeaseCandidateSpec
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1alpha1LeaseCandidateSpec`
        """
        model = V1alpha1LeaseCandidateSpec()
        if include_optional:
            return V1alpha1LeaseCandidateSpec(
                binary_version = '',
                emulation_version = '',
                lease_name = '',
                ping_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                preferred_strategies = [
                    ''
                    ],
                renew_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return V1alpha1LeaseCandidateSpec(
                lease_name = '',
                preferred_strategies = [
                    ''
                    ],
        )
        """

    def testV1alpha1LeaseCandidateSpec(self):
        """Test V1alpha1LeaseCandidateSpec"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
