# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: release-1.31
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes.client.models.v1beta1_ip_address_spec import V1beta1IPAddressSpec

class TestV1beta1IPAddressSpec(unittest.TestCase):
    """V1beta1IPAddressSpec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1beta1IPAddressSpec:
        """Test V1beta1IPAddressSpec
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1beta1IPAddressSpec`
        """
        model = V1beta1IPAddressSpec()
        if include_optional:
            return V1beta1IPAddressSpec(
                parent_ref = kubernetes.client.models.v1beta1/parent_reference.v1beta1.ParentReference(
                    group = '', 
                    name = '', 
                    namespace = '', 
                    resource = '', )
            )
        else:
            return V1beta1IPAddressSpec(
                parent_ref = kubernetes.client.models.v1beta1/parent_reference.v1beta1.ParentReference(
                    group = '', 
                    name = '', 
                    namespace = '', 
                    resource = '', ),
        )
        """

    def testV1beta1IPAddressSpec(self):
        """Test V1beta1IPAddressSpec"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
