# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: release-1.31
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes.client.models.v1_container_user import V1ContainerUser

class TestV1ContainerUser(unittest.TestCase):
    """V1ContainerUser unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1ContainerUser:
        """Test V1ContainerUser
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1ContainerUser`
        """
        model = V1ContainerUser()
        if include_optional:
            return V1ContainerUser(
                linux = kubernetes.client.models.v1/linux_container_user.v1.LinuxContainerUser(
                    gid = 56, 
                    supplemental_groups = [
                        56
                        ], 
                    uid = 56, )
            )
        else:
            return V1ContainerUser(
        )
        """

    def testV1ContainerUser(self):
        """Test V1ContainerUser"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
