# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: release-1.31
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes.client.models.v1alpha3_device_allocation_configuration import V1alpha3DeviceAllocationConfiguration

class TestV1alpha3DeviceAllocationConfiguration(unittest.TestCase):
    """V1alpha3DeviceAllocationConfiguration unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1alpha3DeviceAllocationConfiguration:
        """Test V1alpha3DeviceAllocationConfiguration
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1alpha3DeviceAllocationConfiguration`
        """
        model = V1alpha3DeviceAllocationConfiguration()
        if include_optional:
            return V1alpha3DeviceAllocationConfiguration(
                opaque = kubernetes.client.models.v1alpha3/opaque_device_configuration.v1alpha3.OpaqueDeviceConfiguration(
                    driver = '', 
                    parameters = kubernetes.client.models.parameters.parameters(), ),
                requests = [
                    ''
                    ],
                source = ''
            )
        else:
            return V1alpha3DeviceAllocationConfiguration(
                source = '',
        )
        """

    def testV1alpha3DeviceAllocationConfiguration(self):
        """Test V1alpha3DeviceAllocationConfiguration"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
