# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: release-1.31
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes.client.models.v1_node_features import V1NodeFeatures

class TestV1NodeFeatures(unittest.TestCase):
    """V1NodeFeatures unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1NodeFeatures:
        """Test V1NodeFeatures
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1NodeFeatures`
        """
        model = V1NodeFeatures()
        if include_optional:
            return V1NodeFeatures(
                supplemental_groups_policy = True
            )
        else:
            return V1NodeFeatures(
        )
        """

    def testV1NodeFeatures(self):
        """Test V1NodeFeatures"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
