# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: release-1.31
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes.client.models.v1_field_selector_attributes import V1FieldSelectorAttributes

class TestV1FieldSelectorAttributes(unittest.TestCase):
    """V1FieldSelectorAttributes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1FieldSelectorAttributes:
        """Test V1FieldSelectorAttributes
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1FieldSelectorAttributes`
        """
        model = V1FieldSelectorAttributes()
        if include_optional:
            return V1FieldSelectorAttributes(
                raw_selector = '',
                requirements = [
                    kubernetes.client.models.v1/field_selector_requirement.v1.FieldSelectorRequirement(
                        key = '', 
                        operator = '', 
                        values = [
                            ''
                            ], )
                    ]
            )
        else:
            return V1FieldSelectorAttributes(
        )
        """

    def testV1FieldSelectorAttributes(self):
        """Test V1FieldSelectorAttributes"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
