# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: release-1.31
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes.client.models.v1beta1_service_cidr_status import V1beta1ServiceCIDRStatus

class TestV1beta1ServiceCIDRStatus(unittest.TestCase):
    """V1beta1ServiceCIDRStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1beta1ServiceCIDRStatus:
        """Test V1beta1ServiceCIDRStatus
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1beta1ServiceCIDRStatus`
        """
        model = V1beta1ServiceCIDRStatus()
        if include_optional:
            return V1beta1ServiceCIDRStatus(
                conditions = [
                    kubernetes.client.models.v1/condition.v1.Condition(
                        last_transition_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        message = '', 
                        observed_generation = 56, 
                        reason = '', 
                        status = '', 
                        type = '', )
                    ]
            )
        else:
            return V1beta1ServiceCIDRStatus(
        )
        """

    def testV1beta1ServiceCIDRStatus(self):
        """Test V1beta1ServiceCIDRStatus"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
