# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: release-1.31
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes.client.models.v1alpha3_resource_pool import V1alpha3ResourcePool

class TestV1alpha3ResourcePool(unittest.TestCase):
    """V1alpha3ResourcePool unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1alpha3ResourcePool:
        """Test V1alpha3ResourcePool
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1alpha3ResourcePool`
        """
        model = V1alpha3ResourcePool()
        if include_optional:
            return V1alpha3ResourcePool(
                generation = 56,
                name = '',
                resource_slice_count = 56
            )
        else:
            return V1alpha3ResourcePool(
                generation = 56,
                name = '',
                resource_slice_count = 56,
        )
        """

    def testV1alpha3ResourcePool(self):
        """Test V1alpha3ResourcePool"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
