# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: release-1.31
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes.client.models.v1alpha3_resource_claim_status import V1alpha3ResourceClaimStatus

class TestV1alpha3ResourceClaimStatus(unittest.TestCase):
    """V1alpha3ResourceClaimStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1alpha3ResourceClaimStatus:
        """Test V1alpha3ResourceClaimStatus
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1alpha3ResourceClaimStatus`
        """
        model = V1alpha3ResourceClaimStatus()
        if include_optional:
            return V1alpha3ResourceClaimStatus(
                allocation = kubernetes.client.models.v1alpha3/allocation_result.v1alpha3.AllocationResult(
                    controller = '', 
                    devices = kubernetes.client.models.v1alpha3/device_allocation_result.v1alpha3.DeviceAllocationResult(
                        config = [
                            kubernetes.client.models.v1alpha3/device_allocation_configuration.v1alpha3.DeviceAllocationConfiguration(
                                opaque = kubernetes.client.models.v1alpha3/opaque_device_configuration.v1alpha3.OpaqueDeviceConfiguration(
                                    driver = '', 
                                    parameters = kubernetes.client.models.parameters.parameters(), ), 
                                requests = [
                                    ''
                                    ], 
                                source = '', )
                            ], 
                        results = [
                            kubernetes.client.models.v1alpha3/device_request_allocation_result.v1alpha3.DeviceRequestAllocationResult(
                                device = '', 
                                driver = '', 
                                pool = '', 
                                request = '', )
                            ], ), 
                    node_selector = kubernetes.client.models.v1/node_selector.v1.NodeSelector(
                        node_selector_terms = [
                            kubernetes.client.models.v1/node_selector_term.v1.NodeSelectorTerm(
                                match_expressions = [
                                    kubernetes.client.models.v1/node_selector_requirement.v1.NodeSelectorRequirement(
                                        key = '', 
                                        operator = '', 
                                        values = [
                                            ''
                                            ], )
                                    ], 
                                match_fields = [
                                    kubernetes.client.models.v1/node_selector_requirement.v1.NodeSelectorRequirement(
                                        key = '', 
                                        operator = '', )
                                    ], )
                            ], ), ),
                deallocation_requested = True,
                reserved_for = [
                    kubernetes.client.models.v1alpha3/resource_claim_consumer_reference.v1alpha3.ResourceClaimConsumerReference(
                        api_group = '', 
                        name = '', 
                        resource = '', 
                        uid = '', )
                    ]
            )
        else:
            return V1alpha3ResourceClaimStatus(
        )
        """

    def testV1alpha3ResourceClaimStatus(self):
        """Test V1alpha3ResourceClaimStatus"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
