# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: release-1.31
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes.client.models.v1alpha3_device import V1alpha3Device

class TestV1alpha3Device(unittest.TestCase):
    """V1alpha3Device unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1alpha3Device:
        """Test V1alpha3Device
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1alpha3Device`
        """
        model = V1alpha3Device()
        if include_optional:
            return V1alpha3Device(
                basic = kubernetes.client.models.v1alpha3/basic_device.v1alpha3.BasicDevice(
                    attributes = {
                        'key' : kubernetes.client.models.v1alpha3/device_attribute.v1alpha3.DeviceAttribute(
                            bool = True, 
                            int = 56, 
                            string = '', 
                            version = '', )
                        }, 
                    capacity = {
                        'key' : ''
                        }, ),
                name = ''
            )
        else:
            return V1alpha3Device(
                name = '',
        )
        """

    def testV1alpha3Device(self):
        """Test V1alpha3Device"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
