# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: release-1.31
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes.client.models.v1_resource_attributes import V1ResourceAttributes

class TestV1ResourceAttributes(unittest.TestCase):
    """V1ResourceAttributes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1ResourceAttributes:
        """Test V1ResourceAttributes
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1ResourceAttributes`
        """
        model = V1ResourceAttributes()
        if include_optional:
            return V1ResourceAttributes(
                field_selector = kubernetes.client.models.v1/field_selector_attributes.v1.FieldSelectorAttributes(
                    raw_selector = '', 
                    requirements = [
                        kubernetes.client.models.v1/field_selector_requirement.v1.FieldSelectorRequirement(
                            key = '', 
                            operator = '', 
                            values = [
                                ''
                                ], )
                        ], ),
                group = '',
                label_selector = kubernetes.client.models.v1/label_selector_attributes.v1.LabelSelectorAttributes(
                    raw_selector = '', 
                    requirements = [
                        kubernetes.client.models.v1/label_selector_requirement.v1.LabelSelectorRequirement(
                            key = '', 
                            operator = '', 
                            values = [
                                ''
                                ], )
                        ], ),
                name = '',
                namespace = '',
                resource = '',
                subresource = '',
                verb = '',
                version = ''
            )
        else:
            return V1ResourceAttributes(
        )
        """

    def testV1ResourceAttributes(self):
        """Test V1ResourceAttributes"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
