# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: release-1.31
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes.client.models.v1_image_volume_source import V1ImageVolumeSource

class TestV1ImageVolumeSource(unittest.TestCase):
    """V1ImageVolumeSource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1ImageVolumeSource:
        """Test V1ImageVolumeSource
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1ImageVolumeSource`
        """
        model = V1ImageVolumeSource()
        if include_optional:
            return V1ImageVolumeSource(
                pull_policy = '',
                reference = ''
            )
        else:
            return V1ImageVolumeSource(
        )
        """

    def testV1ImageVolumeSource(self):
        """Test V1ImageVolumeSource"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
