# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: release-1.31
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes.client.models.v1alpha3_cel_device_selector import V1alpha3CELDeviceSelector

class TestV1alpha3CELDeviceSelector(unittest.TestCase):
    """V1alpha3CELDeviceSelector unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1alpha3CELDeviceSelector:
        """Test V1alpha3CELDeviceSelector
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1alpha3CELDeviceSelector`
        """
        model = V1alpha3CELDeviceSelector()
        if include_optional:
            return V1alpha3CELDeviceSelector(
                expression = ''
            )
        else:
            return V1alpha3CELDeviceSelector(
                expression = '',
        )
        """

    def testV1alpha3CELDeviceSelector(self):
        """Test V1alpha3CELDeviceSelector"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
