# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: release-1.31
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes.client.models.v1alpha3_device_attribute import V1alpha3DeviceAttribute

class TestV1alpha3DeviceAttribute(unittest.TestCase):
    """V1alpha3DeviceAttribute unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1alpha3DeviceAttribute:
        """Test V1alpha3DeviceAttribute
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1alpha3DeviceAttribute`
        """
        model = V1alpha3DeviceAttribute()
        if include_optional:
            return V1alpha3DeviceAttribute(
                bool = True,
                int = 56,
                string = '',
                version = ''
            )
        else:
            return V1alpha3DeviceAttribute(
        )
        """

    def testV1alpha3DeviceAttribute(self):
        """Test V1alpha3DeviceAttribute"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
