# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: release-1.31
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from kubernetes.client.models.v1alpha3_device_claim_configuration import V1alpha3DeviceClaimConfiguration
from kubernetes.client.models.v1alpha3_device_constraint import V1alpha3DeviceConstraint
from kubernetes.client.models.v1alpha3_device_request import V1alpha3DeviceRequest
from typing import Optional, Set
from typing_extensions import Self

class V1alpha3DeviceClaim(BaseModel):
    """
    DeviceClaim defines how to request devices with a ResourceClaim.
    """ # noqa: E501
    config: Optional[List[V1alpha3DeviceClaimConfiguration]] = Field(default=None, description="This field holds configuration for multiple potential drivers which could satisfy requests in this claim. It is ignored while allocating the claim.")
    constraints: Optional[List[V1alpha3DeviceConstraint]] = Field(default=None, description="These constraints must be satisfied by the set of devices that get allocated for the claim.")
    requests: Optional[List[V1alpha3DeviceRequest]] = Field(default=None, description="Requests represent individual requests for distinct devices which must all be satisfied. If empty, nothing needs to be allocated.")
    __properties: ClassVar[List[str]] = ["config", "constraints", "requests"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of V1alpha3DeviceClaim from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in config (list)
        _items = []
        if self.config:
            for _item_config in self.config:
                if _item_config:
                    _items.append(_item_config.to_dict())
            _dict['config'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in constraints (list)
        _items = []
        if self.constraints:
            for _item_constraints in self.constraints:
                if _item_constraints:
                    _items.append(_item_constraints.to_dict())
            _dict['constraints'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in requests (list)
        _items = []
        if self.requests:
            for _item_requests in self.requests:
                if _item_requests:
                    _items.append(_item_requests.to_dict())
            _dict['requests'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of V1alpha3DeviceClaim from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "config": [V1alpha3DeviceClaimConfiguration.from_dict(_item) for _item in obj["config"]] if obj.get("config") is not None else None,
            "constraints": [V1alpha3DeviceConstraint.from_dict(_item) for _item in obj["constraints"]] if obj.get("constraints") is not None else None,
            "requests": [V1alpha3DeviceRequest.from_dict(_item) for _item in obj["requests"]] if obj.get("requests") is not None else None
        })
        return _obj


